# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/maia',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/maia',
                'lib_path': 'maia'},
  'syms': {'maia.core': {'maia.core.foo': ('core.html#foo', 'maia/core.py')}}}
